### ISSUE TITLE
API Doc with examples, unit tests for most functions & modules

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#445]
- [x] ./oqs/src/lib.rs (https://github.com/rosenpass/rosenpass/pull/446)
- [x] ./oqs/src/kem_macro.rs (https://github.com/rosenpass/rosenpass/pull/446)
- [x] ./constant-time/src/xor.rs (https://github.com/rosenpass/rosenpass/pull/446, #544)
- [x] ./constant-time/src/lib.rs (https://github.com/rosenpass/rosenpass/pull/446, #544)
- [x] ./constant-time/src/compare.rs (https://github.com/rosenpass/rosenpass/pull/446, #544)
- [x] ./constant-time/src/memcmp.rs (https://github.com/rosenpass/rosenpass/pull/446)
- [x] ./constant-time/src/increment.rs (https://github.com/rosenpass/rosenpass/pull/446, #544)
- [x] ./fuzz/fuzz_targets/blake2b.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/kyber_encaps.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/vec_secret_alloc_malloc.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/box_secret_alloc_memfdsec.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/vec_secret_alloc_memfdsec.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/handle_msg.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/aead_enc_into.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/box_secret_alloc_malloc.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/mceliece_encaps.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/box_secret_alloc_memfdsec_mallocfb.rs (skipped, this is a fuzz test)
- [x] ./fuzz/fuzz_targets/vec_secret_alloc_memfdsec_mallocfb.rs (skipped, this is a fuzz test)
- [x] ./util/src/option.rs (#479)
- [x] ./util/src/mio/mio.rs (#551, #479)
- [x] ./util/src/mio/uds_recv_fd.rs (#551, #479)
- [x] ./util/src/mio/mod.rs (#551)
- [x] ./util/src/mio/uds_send_fd.rs (#479, #563)
- [x] ./util/src/zeroize/zeroized_ext.rs (#479)
- [x] ./util/src/zeroize/mod.rs (#545)
- [x] ./util/src/controlflow.rs (https://github.com/rosenpass/rosenpass/pull/458, #545)
- [x] ./util/src/time.rs (#479)
- [x] ./util/src/functional.rs (https://github.com/rosenpass/rosenpass/pull/458)
- [x] ./util/src/length_prefix_encoding/mod.rs (#479)
- [x] ./util/src/length_prefix_encoding/decoder.rs (#526, #479, #538)
- [x] ./util/src/length_prefix_encoding/encoder.rs (#479, #489, #500)
- [x] ./util/src/fd.rs (https://github.com/rosenpass/rosenpass/pull/458, #479, #545)
- [x] ./util/src/b64.rs (https://github.com/rosenpass/rosenpass/pull/446)
- [x] ./util/src/zerocopy/ref_maker.rs (#527, #479, #532)
- [x] ./util/src/zerocopy/mod.rs (#527, #479, #532)
- [x] ./util/src/zerocopy/zerocopy_slice_ext.rs (#527, #479, #532)
- [x] ./util/src/zerocopy/zerocopy_ref_ext.rs (#527, #479, #532)
- [x] ./util/src/mem.rs (#479, #545)
- [x] ./util/src/result.rs (#479, #545)
- [x] ./util/src/build.rs (https://github.com/rosenpass/rosenpass/pull/446, #545)
- [x] ./util/src/typenum.rs (#479, #545)
- [x] ./util/src/file.rs (https://github.com/rosenpass/rosenpass/pull/458)
- [x] ./util/src/lib.rs (#489)
- [x] ./util/src/io.rs (https://github.com/rosenpass/rosenpass/pull/458, #479, #545)
- [x] ./cipher-traits/src/kem.rs (#529, #543, #542)
- [x] ./cipher-traits/src/lib.rs (#529, #543)
- [x] ./secret-memory/src/secret.rs (#531)
- [x] ./secret-memory/src/lib.rs (#531)
- [x] ./secret-memory/src/public.rs (#531)
- [x] ./secret-memory/src/rand.rs (#531)
- [x] ./secret-memory/src/policy.rs (#531)
- [x] ./secret-memory/src/debug.rs (#531)
- [x] ./secret-memory/src/alloc/memsec/mod.rs (#531)
- [x] ./secret-memory/src/alloc/memsec/malloc.rs (#531)
- [x] ./secret-memory/src/alloc/memsec/memfdsec.rs (#531)
- [x] ./secret-memory/src/alloc/mod.rs (#531)
- [x] ./secret-memory/src/file.rs (#531)
- [x] ./rp/src/key.rs (#528, #565)
- [x] ./rp/src/cli.rs (#528, #565)
- [x] ./rp/src/exchange.rs (#528, #565)
- [x] ./rp/src/main.rs (#528, #565)
- [x] ./to/src/ops.rs (#546)
- [x] ./to/src/lib.rs  (#546, #479)
- [x] ./to/src/to/mod.rs (#546)
- [x] ./to/src/to/to_trait.rs (#546, #479)
- [x] ./to/src/to/dst_coercion.rs (#546, #479)
- [x] ./to/src/to/with_destination.rs (#546, #479)
- [x] ./to/src/to/condense.rs (#546, #479)
- [x] ./to/src/to/beside.rs (#546, #479)
- [x] ./to/src/to/to_function.rs (#546)
- [x] ./rosenpass/tests/api-integration-tests-api-setup.rs (Integration test, no doc or unit tests needed)
- [x] ./rosenpass/tests/api-integration-tests.rs (Integration test, no doc or unit tests needed)
- [x] ./rosenpass/tests/integration_test.rs (Integration test, no doc or unit tests needed)
- [x] ./rosenpass/build.rs (build script, removed by now)
- [x] ./rosenpass/benches/handshake.rs (benchmark, no doc or unit tests needed)
- [x] ./rosenpass/src/main.rs (#520)
- [x] ./rosenpass/src/cli.rs (#560)
- [x] ./rosenpass/src/msgs.rs (#520)
- [x] ./rosenpass/src/app_server.rs (#552)
- [x] ./rosenpass/src/hash_domains.rs (#520)
- [x] ./rosenpass/src/lib.rs (#520)
- [x] ./rosenpass/src/protocol/mod.rs (#520)
- [x] ./rosenpass/src/protocol/build_crypto_server.rs (#568)
- [x] ./rosenpass/src/protocol/protocol.rs (#537)
     - [x] Most of the file (#537)
     - [x] Example of using the protocol with Poll (#537)
     - [x] Example of using the protocol with cookie handling (#537)
     - [ ] Stretch goals (see below)
     - [ ] Examples for HandshakeState
- [x] ./rosenpass/src/config.rs (#560)
- [x] ./rosenpass/src/api/config.rs (https://github.com/rosenpass/rosenpass/commit/47b556e317c1e3d3b45b7d5b28481956082577de, #568)
- [x] ./rosenpass/src/api/cli.rs (#566, #568)
- [x] ./rosenpass/src/api/mio/mod.rs (https://github.com/rosenpass/rosenpass/commit/0ea9f1061ee3f7052fa632bb4dd80bdcace0a33e, #568)
- [x] ./rosenpass/src/api/mio/connection.rs (#568)
- [x] ./rosenpass/src/api/mio/manager.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/request_response.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/byte_slice_ext.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/response_ref.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/payload.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/message_type.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/message_trait.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/mod.rs (#568)
- [x] ./rosenpass/src/api/boilerplate/server.rs (#512), #568)
- [x] ./rosenpass/src/api/boilerplate/request_ref.rs (#568)
- [x] ./rosenpass/src/api/mod.rs (#520, #568)
- [x] ./rosenpass/src/api/api_handler.rs (#512, #568)
- [x] ./rosenpass/src/bin/gen-ipc-msg-types.rs (#520, but only very basic – this is a developer tool) 
- [x] ./ciphers/src/lib.rs (#506)
- [x] ./ciphers/src/hash_domain.rs (#506, #549)
- [x] ./ciphers/src/subtle/chacha20poly1305_ietf_libcrux.rs (#506)
- [x] ./ciphers/src/subtle/incorrect_hmac_blake2b.rs (#506)
- [x] ./ciphers/src/subtle/xchacha20poly1305_ietf.rs (#506)
- [x] ./ciphers/src/subtle/blake2b.rs (#506, #543)
- [x] ./ciphers/src/subtle/chacha20poly1305_ietf.rs (#506)
- [x] ./ciphers/src/subtle/mod.rs (#506, #543)
- [x] ./wireguard-broker/src/api/mod.rs (#550)
- [x] ./wireguard-broker/src/api/config.rs (#550)
- [x] ./wireguard-broker/src/api/msgs.rs (#550)
- [x] ./wireguard-broker/src/api/server.rs (#550)
- [x] ./wireguard-broker/src/api/client.rs (#550)
- [x] ./wireguard-broker/src/bin/socket_handler.rs (#550)
- [x] ./wireguard-broker/src/bin/priviledged.rs (#550)
- [x] ./wireguard-broker/src/lib.rs (#550)
- [x] ./wireguard-broker/src/brokers/mio_client.rs (#550)
- [x] ./wireguard-broker/src/brokers/netlink.rs (#550)
- [x] ./wireguard-broker/src/brokers/mod.rs (#550)
- [x] ./wireguard-broker/src/brokers/native_unix.rs (#550)

To help us figure out which unit tests are missing in the unix socket API, we need to have accurate coverage metrics.

- [x] Incorporate integration tests for unix socket API in coverage (#523)
- [x] #548 
- [x] #564

# Issues fixed or found

- #534 (fixed in #537)
- #539  (open)
- #541 (open)

# Stretch Goals

## Function examples

A lot of functions are concerned with finicky business logic, especially in the `rosenpass` crate itself. Adding examples for these functions is hard because the setup code often dominates and the real code we use often serves as a better reference than the examples we could write. Many of these are also oneliner functions, leading to a massive effort to document and add examples compared to what the function actually does.

### rosenpass::protocol::protocol

- [ ] IniHsPtr::insert
- [ ] IniHsPtr::take
- [ ] SessionPtr::insert
- [ ] SessionPtr::take
- [ ] BiscuitKeyPtr::get
- [ ] BiscuitKeyPtr::get_mut
- [ ] ServerCookieSecretPtr::get
- [ ] ServerCookieSecretPtr::get_mut
- [ ] KnownInitConfResponsePtr::remove
- [ ] KnownInitConfResponsePtr::insert
- [ ] KnownInitConfResponsePtr::lookup_for_request_msg
- [ ] KnownInitConfResponsePtr::insert_for_request_msg
- [ ] KnownInitConfResponsePtr::index_key_for_hash_msg
- [ ] KnownInitConfResponsePtr::index_key_for_msg
- [ ] CryptoServer::biscuit_key_ptrs
- [ ] CryptoServer::cookie_secret_ptrs
- [ ] CryptoServer::pidm
- [ ] CryptoServer::peer_ptrs_off
- [ ] CryptoServer::register_session
- [ ] CryptoServer::unregister_session
- [ ] CryptoServer::unregister_session_if_vacant
- [ ] CryptoServer::find_peer
- [ ] CryptoServer::lookup_handshake
- [ ] CryptoServer::lookup_session
- [ ] CryptoServer::active_biscuit_key
- [ ] CryptoServer::active_or_retired_cookie_secrets
- [x] Peer::new
- [x] Peer::pidt
- [x] Session::new
- [ ] CookieStore::new
- [ ] CryptoServer::handle_msg_under_load
- [ ] CryptoServer::seal_and_commit_msg
- [ ] Pollable::poll
- [ ] IniHsPtr::store_msg_for_retransmission
- [ ] IniHsPtr::apply_retransmission
- [ ] IniHsPtr::register_retransmission
- [ ] IniHsPtr::register_immediate_retransmission
- [ ] IniHsPtr::retransmission_in
- [ ] truncating_cast_into
- [ ] truncating_cast_into_nomut
- [ ] CryptoServer::handle_init_conf
- [ ] CryptoServer::handle_cookie_reply
- [ ] CryptoServer::handle_init_hello
- [ ] CryptoServer::handle_resp_hello
- [ ] CryptoServer::handle_resp_conf

## Example about how to use the API

It does not make sense to add a lot of examples or unit tests to the rosenpass::api module, since it contains a ton of business logic. We should however, provide one, central example of how to set up a server using the API.

- [x] Central example of how to use the API (#568)

**Comment by aparcar** [comment]
This is a first take to fix docstring warnings: https://github.com/rosenpass/rosenpass/pull/479
